---
version: "3.8"
services:

 gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=US atlanta
    restart: always

 qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
     - /media/vikingr:/downloads
     - /media/arr/qbittorrent:/config
    restart: always
    depends_on: 
      - gluetun

 prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /media/arr/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

 radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /media/vikingr:/downloads
      - /media/arr/radarr:/config
      - /media:/plex
    ports:
      - 7878:7878
    restart: unless-stopped 

 sonarr:
  image: lscr.io/linuxserver/sonarr:latest
  container_name: sonarr
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
  volumes:
    - /media/vikingr:/downloads
    - /media/arr/sonarr:/config
    - /media:/plex
  ports:
    - 8989:8989
  restart: unless-stopped

 overseerr:
  image: lscr.io/linuxserver/overseerr:latest
  container_name: overseerr
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
  volumes:
    - /media/arr/overseer:/config
    - /media:/plex
  ports:
    - 5055:5055
  restart: unless-stopped

 portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /media/arr/portainer:/data
    restart: always

